### ISSUE TITLE
長いインラインコードブロックが画面からはみ出して一部読めない

### ISSUE THREAD

**Issue by Raclamusi** [cpprefjp/kunai#142]
インラインコードブロックの中では改行されず、長いインラインコードブロックは、特にスマートフォンなど横幅の小さい環境で画面からはみ出して一部読めなくなっています。

<img width="400" alt="スクリーンショット" src="https://github.com/cpprefjp/kunai/assets/61970673/66bbf3cc-1e6a-4c68-b2cf-fe0c01fbe8e3">

### 修正案

インラインコードブロック内の改行を許可することで解決できます。
例えば、以下のスタイルを追加する方法があります。

```css
/* css/kunai/site/article.css */
div[itemtype="http://schema.org/Article"] {
  :not(pre)>code {
    display: inline-table;
    white-space: pre-wrap;
  }
}
```

<img width="400" alt="スクリーンショット" src="https://github.com/cpprefjp/kunai/assets/61970673/4eb25ea2-5ff6-4df1-be90-c8f8b752dd05">
